### PR TITLE
Respect custom paths in service descriptions

### PR DESCRIPTION
**Pull request by mobin-2008**
Replace fixed paths in services with a in build-time configurable value. All files in `services/` are `.in` files now, these files get resolved by meson.

`Signed-off-by: Mobin Aydinfar <mobin@mobintestserver.ir>`

### CODE REVIEW

**Comment by mobin-2008** [comment]
@q66 ?

**Comment by q66** [comment]
while i'm not against having some degree of configurability for the paths, this is not the way to go, and it interferes with other things i'm working on right now, so i'll just close this one

i'll probably do this myself later but in a different way

**Comment by q66** [comment]
i have some early work towards that goal in https://github.com/chimera-linux/dinit-chimera/tree/script-path-unify, for now untested

**Comment by mobin-2008** [comment]
Thanks, I will test it

**Comment by q66** [comment]
it doesn't work yet

**Pull request closed without merging**
